const f4 = (v) => Number(v).toFixed(4);
const vec = (arr) => `(${arr.map(f4).join(", ")})`;

function faceToCode(face) {
  const p = face.params ?? {};
  const varName = `surface_${face.id}`;
  const lines = [`# Face ${face.id} — ${face.type}`];

  if (face.type === "plane" && p.origin && p.normal) {
    lines.push(`${varName} = Surface.plane(`);
    lines.push(`    origin=${vec(p.origin)},`);
    lines.push(`    normal=${vec(p.normal)},`);
    lines.push(`    name="face_${face.id}",`);
    lines.push(`)`);
  } else if (face.type === "cylinder" && p.center != null && p.radius != null) {
    const axis = p.axis ?? [0, 0, 1];
    const height = p.height != null ? f4(p.height) : "100.0  # estimate";
    lines.push(`${varName} = Surface.cylinder(`);
    lines.push(`    center=${vec(p.center)},`);
    lines.push(`    axis=${vec(axis)},`);
    lines.push(`    radius=${f4(p.radius)},`);
    lines.push(`    height=${height},`);
    lines.push(`    name="face_${face.id}",`);
    lines.push(`)`);
  } else if (face.type === "sphere" && p.center != null && p.radius != null) {
    lines.push(`${varName} = Surface.sphere(`);
    lines.push(`    center=${vec(p.center)},`);
    lines.push(`    radius=${f4(p.radius)},`);
    lines.push(`    name="face_${face.id}",`);
    lines.push(`)`);
  } else {
    lines.push(`# ${face.type} — no direct Surface mapping`);
    lines.push(`${varName} = None  # TODO: implement for '${face.type}'`);
  }
  return { varName, lines };
}

function edgeToCode(edge) {
  const p = edge.params ?? {};
  const varName = `curve_${edge.id}`;
  const lines = [`# Edge ${edge.id} — ${edge.type}`];

  if (edge.type === "circle" && p.center != null && p.radius != null) {
    const axis = p.axis ?? [0, 0, 1];
    lines.push(`${varName} = Curve.circle(`);
    lines.push(`    center=${vec(p.center)},`);
    lines.push(`    radius=${f4(p.radius)},`);
    lines.push(`    normal=${vec(axis)},`);
    lines.push(`    num_points=64,`);
    lines.push(`)`);
  } else if (edge.type === "line" && p.start && p.end) {
    lines.push(`${varName} = Curve.line(`);
    lines.push(`    start=${vec(p.start)},`);
    lines.push(`    end=${vec(p.end)},`);
    lines.push(`)`);
  } else if (p.points && p.points.length) {
    // Generic: spline through sampled points
    const ptList = p.points.slice(0, 20).map(pt => `        ${vec(pt)}`).join(",\n");
    lines.push(`${varName} = Curve.spline(`);
    lines.push(`    control_points=[\n${ptList}\n    ],`);
    lines.push(`    num_points=100,`);
    lines.push(`)`);
  } else {
    lines.push(`${varName} = None  # TODO: implement for '${edge.type}'`);
  }
  return { varName, lines };
}

function orientationRuleToCode(rule, surfaceVars, curveVars) {
  switch (rule.rule) {
    case "to_normal": {
      const ref = surfaceVars[rule.surface_id] ?? "surface_0";
      return `paths.orient(to_normal(${ref}))`;
    }
    case "fixed":
      return `paths.orient(fixed(${rule.i ?? 0}, ${rule.j ?? 0}, ${rule.k ?? -1}))`;
    case "lead":
      return `paths.orient(lead(${rule.angle_deg ?? 10}))`;
    case "lag":
      return `paths.orient(lag(${rule.angle_deg ?? 5}))`;
    case "side_tilt":
      return `paths.orient(side_tilt(${rule.angle_deg ?? 5}))`;
    case "avoid_collision":
      return `paths.orient(avoid_collision(machine, max_tilt=${rule.max_tilt ?? 45}))`;
    default:
      return `# unknown rule: ${rule.rule}`;
  }
}

export function generatePythonCode(faces, edges, strategy, orientationRules, machine = "gantry_5axis_ac") {
  const faceResults = faces.map(faceToCode);
  const edgeResults = edges.map(edgeToCode);

  // Build lookup maps for orientation rule code gen
  const surfaceVars = {};
  faces.forEach((f, i) => { surfaceVars[f.id] = faceResults[i].varName; });
  const curveVars = {};
  edges.forEach((e, i) => { curveVars[e.id] = edgeResults[i].varName; });

  const lines = [
    "# Generated by UTDE Toolpath Visualizer",
    "from toolpath_engine import (",
    "    Surface, Curve, GeometryModel,",
    "    FollowCurveStrategy, RasterFillStrategy, ContourParallelStrategy,",
    "    to_normal, fixed, lead, lag, side_tilt, avoid_collision,",
    "    Machine, PostProcessor, PostConfig,",
    ")",
    "",
    "# ── Geometry ─────────────────────────────────────────────",
    'model = GeometryModel(name="imported_step")',
    "",
  ];

  // Surfaces
  faceResults.forEach(({ varName, lines: fLines }) => {
    lines.push(...fLines);
    lines.push(`if ${varName}:`);
    lines.push(`    model.add_surface(${varName}, tags=["imported"])`);
    lines.push("");
  });

  // Curves
  edgeResults.forEach(({ varName, lines: eLines }) => {
    lines.push(...eLines);
    lines.push(`if ${varName}:`);
    lines.push(`    model.add_curve(${varName}, tags=["imported"])`);
    lines.push("");
  });

  // Machine
  lines.push("# ── Machine ──────────────────────────────────────────────");
  lines.push(`machine = Machine.${machine}(name="my_machine")`);
  lines.push("");

  // Strategy
  lines.push("# ── Toolpath strategy ────────────────────────────────────");
  const firstEdge = edgeResults[0]?.varName;
  const firstSurface = faceResults[0]?.varName;

  if (strategy.type === "follow_curve" && firstEdge) {
    lines.push(`paths = FollowCurveStrategy().generate(`);
    lines.push(`    curve=${firstEdge},`);
    lines.push(`    feed_rate=${strategy.feed_rate},`);
    lines.push(`    spacing=${strategy.spacing},`);
    lines.push(`    path_type="${strategy.path_type}",`);
    lines.push(`)`);
  } else if (strategy.type === "raster_fill" && firstSurface) {
    lines.push(`paths = RasterFillStrategy().generate(`);
    lines.push(`    surface=${firstSurface},`);
    lines.push(`    spacing=${strategy.spacing},`);
    lines.push(`    feed_rate=${strategy.feed_rate},`);
    lines.push(`    angle=${strategy.angle},`);
    lines.push(`    zigzag=${strategy.zigzag ? "True" : "False"},`);
    lines.push(`)`);
  } else if (strategy.type === "contour_parallel") {
    const ref = firstEdge ?? firstSurface ?? "None";
    lines.push(`paths = ContourParallelStrategy().generate(`);
    lines.push(`    boundary=${ref},`);
    lines.push(`    stepover=${strategy.stepover},`);
    lines.push(`    num_passes=${strategy.num_passes},`);
    lines.push(`    feed_rate=${strategy.feed_rate},`);
    lines.push(`)`);
  } else {
    lines.push("# TODO: configure a strategy");
    lines.push("paths = None");
  }
  lines.push("");

  // Orientation
  if (orientationRules.length > 0) {
    lines.push("# ── Orientation rules ────────────────────────────────────");
    orientationRules.forEach((rule) => {
      lines.push(orientationRuleToCode(rule, surfaceVars, curveVars));
    });
    lines.push("");
  }

  // Post-process
  lines.push("# ── G-code output ────────────────────────────────────────");
  lines.push("post = PostProcessor(machine)");
  lines.push("gcode = post.process(paths)");
  lines.push("");
  lines.push('with open("output.nc", "w") as f:');
  lines.push("    f.write(gcode)");
  lines.push('print("Saved output.nc")');

  return lines.join("\n");
}
