import { describe, it, expect } from "vitest";
import { graphToScript } from "../../components/ScriptView/graphToScript";

// Minimal graphStore state fixtures
const baseState = (strategyType, orientRules = []) => ({
  nodes: [
    {
      id: "node_geo",
      type: "geometry",
      params: { selected_face_ids: [], selected_edge_ids: [] },
      input_ports: [],
      output_ports: [],
    },
    {
      id: "node_strategy",
      type: "strategy",
      params: {
        strategy_type: strategyType,
        feed_rate: 600,
        spacing: 2.0,
        angle: 0,
        zigzag: true,
        stepover: 3.0,
        num_passes: 4,
        path_type: "cut",
      },
      input_ports: [],
      output_ports: [],
    },
    ...orientRules.map((r, i) => ({
      id: `node_orient_${i}`,
      type: "orient",
      params: r,
      input_ports: [],
      output_ports: [],
    })),
    {
      id: "node_post",
      type: "post_processor",
      params: { machine: "gantry_5axis_ac" },
      input_ports: [],
      output_ports: [],
    },
  ],
  edges: [
    { id: "e1", from_node: "node_strategy", from_port: "toolpath_out", to_node: "node_post", to_port: "toolpath_in" },
  ],
});

describe("graphToScript", () => {
  it("returns a string", () => {
    const code = graphToScript(baseState("follow_curve"), [], []);
    expect(typeof code).toBe("string");
    expect(code.length).toBeGreaterThan(0);
  });

  it("includes UTDE header comment", () => {
    const code = graphToScript(baseState("follow_curve"), [], []);
    expect(code).toContain("Generated by UTDE");
  });

  it("includes FollowCurveStrategy for follow_curve", () => {
    const code = graphToScript(baseState("follow_curve"), [], []);
    expect(code).toContain("FollowCurveStrategy");
  });

  it("includes RasterFillStrategy for raster_fill", () => {
    const code = graphToScript(baseState("raster_fill"), [], []);
    expect(code).toContain("RasterFillStrategy");
  });

  it("includes ContourParallelStrategy for contour_parallel", () => {
    const code = graphToScript(baseState("contour_parallel"), [], []);
    expect(code).toContain("ContourParallelStrategy");
  });

  it("includes orient rule when present", () => {
    const state = baseState("follow_curve", [{ rule: "lead", angle_deg: 10 }]);
    const code = graphToScript(state, [], []);
    expect(code).toContain("lead(10)");
  });

  it("includes machine preset", () => {
    const code = graphToScript(baseState("follow_curve"), [], [], "cartesian_3axis");
    expect(code).toContain("Machine.cartesian_3axis");
  });

  it("includes PostProcessor", () => {
    const code = graphToScript(baseState("follow_curve"), [], []);
    expect(code).toContain("PostProcessor");
  });

  it("includes geometry code for passed faces", () => {
    const face = {
      id: "face_0",
      type: "plane",
      params: { origin: [0, 0, 0], normal: [0, 0, 1] },
    };
    const code = graphToScript(baseState("follow_curve"), [face], []);
    expect(code).toContain("Surface.plane");
  });

  it("includes geometry code for passed edges", () => {
    const edge = {
      id: "edge_0",
      type: "circle",
      params: { center: [0, 0, 0], radius: 10, axis: [0, 0, 1] },
    };
    const code = graphToScript(baseState("follow_curve"), [], [edge]);
    expect(code).toContain("Curve.circle");
  });
});
