import { describe, it, expect, vi, beforeEach } from "vitest";
import { render, screen, fireEvent } from "@testing-library/react";
import PostTab from "../../components/post/PostTab";
import { useToolpathStore } from "../../store/toolpathStore";
import { useUiStore } from "../../store/uiStore";
import { useStepStore } from "../../store/stepStore";

vi.mock("../../components/viewport/StepViewport", () => ({
  default: () => <div data-testid="step-viewport" />,
}));

vi.mock("../../lib/templateLoader", () => ({
  useTemplates: () => ({
    templates: [{ id: "pocket", est_time: 4.6 }],
    loading: false, error: null,
  }),
}));

const saveGcodeDialog = vi.fn().mockResolvedValue("/tmp/out.nc");
vi.mock("../../lib/backend", () => ({
  IS_TAURI: false,
  saveGcodeDialog: (...args) => saveGcodeDialog(...args),
  getBaseUrl: vi.fn().mockResolvedValue("/api"),
  waitForServer: vi.fn().mockResolvedValue(undefined),
  openStepFileDialog: vi.fn(),
}));

const SAMPLE_GCODE = `(--- OP 01  Pocket ---)
( Generated by UTDE )
G90
G21
G1 X10 Y20 Z-1 F1200
G1 X20 Y20
(--- OP 02  Deposit ---)
G1 X30 Y30 Z-1 F1800
G1 X40 Y30`;

const SAMPLE_OP_RANGES = [
  { idx: 0, kind: "sub", name: "Pocket",  templateId: "pocket",
    gcode_start_line: 0, gcode_end_line: 6 },
  { idx: 1, kind: "add", name: "Deposit", templateId: "deposit-layer",
    gcode_start_line: 6, gcode_end_line: 9 },
];

function seed() {
  useToolpathStore.setState({
    toolpaths: [], activeIds: new Set(), animProgress: 0,
    isAnimating: false, simSpeed: 1,
    gcode: SAMPLE_GCODE, opRanges: SAMPLE_OP_RANGES,
    warnings: [], isCompiling: false, compileError: null,
  });
  useUiStore.setState({ tab: "post", showToolpaths: false });
  useStepStore.setState({ fileName: "bracket.step" });
}

beforeEach(() => {
  saveGcodeDialog.mockClear();
  seed();
});

describe("PostTab — empty state", () => {
  it("shows the run-setup nudge when there is no G-code", () => {
    useToolpathStore.setState({
      gcode: "", opRanges: [], warnings: [],
      toolpaths: [], activeIds: new Set(),
    });
    render(<PostTab />);
    expect(screen.getByText(/No G-code yet/i)).toBeInTheDocument();
    expect(screen.getByText(/Run setup/i)).toBeInTheDocument();
  });

  it("disables Export when there is no G-code", () => {
    useToolpathStore.setState({
      gcode: "", opRanges: [], warnings: [],
      toolpaths: [], activeIds: new Set(),
    });
    render(<PostTab />);
    const exportBtn = screen.getByRole("button", { name: /Export \.nc/i });
    expect(exportBtn).toBeDisabled();
  });
});

describe("PostTab — populated", () => {
  it("renders meta bar with machine, lines, cycle time, warnings", () => {
    render(<PostTab />);
    expect(screen.getByText("Machine")).toBeInTheDocument();
    expect(screen.getByText("HMC-470")).toBeInTheDocument();
    expect(screen.getByText("Lines")).toBeInTheDocument();
    expect(screen.getByText("Cycle time")).toBeInTheDocument();
    expect(screen.getByText("Warnings")).toBeInTheDocument();
    // 9 lines in the sample G-code: the meta-bar value should appear
    expect(screen.getAllByText("9").length).toBeGreaterThan(0);
  });

  it("renders the op-divider gcode lines", () => {
    render(<PostTab />);
    expect(screen.getByText(/--- OP 01\s+Pocket ---/)).toBeInTheDocument();
    expect(screen.getByText(/--- OP 02\s+Deposit ---/)).toBeInTheDocument();
  });

  it("highlights G-codes and coordinates in the gcode view", () => {
    render(<PostTab />);
    // G1 appears multiple times — its rendered span should have the code colour.
    const g1 = screen.getAllByText("G1")[0];
    expect(g1).toHaveStyle({ color: "oklch(50% 0.13 260)" });
    const x10 = screen.getByText("X10");
    expect(x10).toHaveStyle({ color: "oklch(50% 0.12 25)" });
  });

  it("forces showToolpaths to true on mount", () => {
    render(<PostTab />);
    expect(useUiStore.getState().showToolpaths).toBe(true);
  });

  it("shows a scrubber when toolpaths exist and scrubbing sets progress", () => {
    useToolpathStore.setState({
      toolpaths: [
        { id: 1, label: "op", color: "#fff", visible: true,
          points: [{ x: 0, y: 0, z: 0 }, { x: 1, y: 0, z: 0 }] },
      ],
      activeIds: new Set([1]),
    });
    render(<PostTab />);
    const slider = screen.getByLabelText("Scrub toolpath preview");
    expect(slider).toBeInTheDocument();
    fireEvent.change(slider, { target: { value: "0.5" } });
    expect(useToolpathStore.getState().animProgress).toBeCloseTo(0.5, 3);
  });

  it("hides the scrubber when there are no toolpaths", () => {
    render(<PostTab />); // seeded with toolpaths: []
    expect(screen.queryByLabelText("Scrub toolpath preview")).toBeNull();
  });

  it("clicking Export creates a blob URL and triggers a download anchor", async () => {
    const clickSpy = vi.fn();
    let lastAnchor = null;

    const realCreate = document.createElement.bind(document);
    vi.spyOn(document, "createElement").mockImplementation((tag) => {
      const el = realCreate(tag);
      if (tag === "a") {
        el.click = clickSpy;
        lastAnchor = el;
      }
      return el;
    });
    window.URL.createObjectURL = vi.fn(() => "blob:mock");
    window.URL.revokeObjectURL = vi.fn();

    render(<PostTab />);
    fireEvent.click(screen.getByRole("button", { name: /Export \.nc/i }));

    expect(window.URL.createObjectURL).toHaveBeenCalled();
    expect(clickSpy).toHaveBeenCalled();
    expect(lastAnchor.download).toBe("bracket.nc");
  });
});
